import { db } from "./firebase";
import { collection, addDoc, getDocs, query, where, writeBatch, doc } from "firebase/firestore";

const classes = {
  "1 Amanah": [
    "AAFIYAH NAYLA BINTI RAJIS", "ADRA HUMAIRA BINTI MOKTARRUDIN", "AL KAHFI BIN SULAIMAN", "ALIMUDDIN BIN MIZPAL",
    "AMMAR ASHRAF BIN MOHAMMAD HAIRI SYAH", "AWIRA BIN JAFRI", "FREDOLIN RUMANEH", "HARRIS QAISER BIN MOHD KHAIRIE",
    "HAYYAN SHIRAZ BIN MOHD SABRIE", "ISAAC ZAFRAN BIN FAZIEZIE", "JENNA MALAEQA BINTI JUFRI", "MAWAR ADELLIA BINTI MOHD FIKRINIMAH",
    "MOHAMMAD AYDEENSHAH ISYHRAAF BIN AFENDI TONA", "MUHAMMAD AZHAD SHARZNAS BIN MOHD SHARIL", "MUHAMMAD IFFAT ANDRIAS BIN MOHD SHAFIQ",
    "MUHAMMAD KASYAF ARIEF BIN AMIN RASYIDI", "MUHAMMAD KHALISH ARYAN BIN ABDULLAH", "NABILA YARA BINTI NIZAM ZUL ELMI",
    "NUR AFIFAH AZZAHRA BINTI BINARD", "NUR AFIYAH AAIRA BINTI ABDULLAH", "NUR AULIYA MAISARAH BINTI MOHD AFFINDY",
    "NUR FATEHA BINTI YASIN", "NUR PUTRI ALISYA BINTI MUHAMMAD SYAFIE", "QALISHA MIQAYLA BINTI MOHD RAFIE",
    "RAISYA AZZAHRA BINTI BUSTANI", "RAISYA IMANI BINTI RAHIMI", "RAYQA BINTI ISHAK", "RIZQ ZARIF BIN RAZUIL",
    "SANAN KHAN BIN SHAHID KHAN", "SOFIYA AMARA BINTI ABDUL RAHMAN", "SYAFIYAH BINTI JAMALEY", "UWAIS ALQORNI BIN ABDULLAH"
  ],
  "1 Bestari": [
    "AIDAN AQIL", "AISYAH KHAIRUNNISA BINTI MOHD KHAIRY", "ALSHAYATINA BINTI ABDULLAH", "AMSYAR YAZID BIN BAKRI",
    "ARRYAN DZHAFRY BIN ELMER ZACHARY", "AWANG JAFIZAL DANISH BIN AG JAMADIL", "FARIS SUFIAN BIN ABDULLAH",
    "FATIN NUR KHAYLA BINTI MOHD. ZUL HANAFIAH", "HANA NAJLA BINTI MOHAMMAD MAHATHIR", "HEMI AFRAKAYLA SYAEZA BINTI MOHD SHARIZAN",
    "INAS MIRZA BINTI NAZRAEN", "JANNATUL BATRIESYAH BINTI NIRZUAN SHAH", "MOHAMMAD AIDIEL BIN ANDIAN GOH",
    "MUHAMMAD ARYAN BIN ARIFF AMIRUL", "MUHAMMAD AZIM BIN ABDUL HALIM", "MUHAMMAD AZZHAD DARWISY BIN MOHD ARIZAN",
    "MUHAMMAD FAQIH RAIQAL BIN MOHD FAIZAL", "MUHAMMAD PUTRA RAFAEL BIN JAMAL", "MUHAMMAD QAYYIM IFFAT BIN ABDULLAH",
    "MUHAMMAD QHAYS AMSYAR BIN REMIE", "MUHAMMAD SHARIFUL ATID BIN HUSIN", "NUR AAIRA AAFIYAH BINTI ABDULLAH",
    "NUR AIFA BINTI AFIAN", "NUR DAHLIA HAFIYA BINTI ABDULLAH", "NUR HANA HUMAIRA BINTI DARAHMAN",
    "NUR HANANAH AAFIYAH BINTI MOHD HAZARIE ALWIE LEE", "NUR HUMAIRAH FATRISYA BINTI MOHD AZWAN", "PUTRI KHALISYA BINTI ABDULLAH",
    "PUTRI NUR AIRA BATRISYA BINTI MOHAMAD AKHRAM", "SITI KHADIJAH BINTI JAVIR", "SITI NUR HIDAYAH BINTI ABDULLAH",
    "SYAH ISKANDAR BIN JAHAR", "MOHAMMAD NAZRUL BIN ABDULLAH"
  ],
  "2 Amanah": [
    "AISY ANAQI BIN MOHD SAIDAH", "ARASHEL LEONG JIA YING", "AZFAR ABQARI BIN AWANG FEDLY", "BIBI RAIHANA BINTI RUDY",
    "INTAN ERLIYANA BINTI ERWAN", "MUAZ RIZQ ABADI BIN SAIFUL ABADI", "MUHAMMAD ADIB BIN SARIWAN", "MUHAMMAD AQIF KASYAF BIN AZIZAL",
    "MUHAMMAD ASHRAF BIN DARAHMAN", "MUHAMMAD FAIZ AIZAT BIN YUSRI FAZLEY", "MUHAMMAD FIRASH QALISH BIN ABDULLAH",
    "MUHAMMAD FUDHAIL BIN MOHD KHAIRUL AIZAT", "MUHAMMAD HAMIZ HARRAZ BIN AMIRULIZWAN", "MUHAMMAD MUAZ BIN MUSA",
    "MUHAMMAD QAYYEM QUZYAIRI BIN AZIZUL", "MUHAMMAD RAFIQIE BIN RIZAL", "MUHAMMAD UZAYR DANIAL BIN SUHAIMI",
    "MUHAMMAD ZEESHAN RAYEEF BIN AG ASRULIZAM", "NUR ALIA AARA BINTI ABDULLAH", "NUR HAWA HUMAIRAH BINTI MAZRUL",
    "NURUL QALEA NAFEEYA BINTI MOHAMAD REDZUAN SHAH", "PUTRI DAYANA DELISHA BINTI AZAHARIZA IDZUAN",
    "PUTRI NUR SYAQEELA SOFEA BINTI MOHAMAD NOR YAZIN", "SHIRAZ RAIQAL BIN JAMAL ABDILLAH", "YUSUF BIN AFIZAN",
    "AINEZ SALILIE SAFRINAH BINTI RAZLAN", "MOHAMAD JAILANI BIN ABDULLAH"
  ],
  "2 Bestari": [
    "AFIKREDUANDY BIN AFFENDY", "ANUM ARISYA BINTI ABDULLAH", "DANIEL SYAFRAN BIN MOHD SOFIAN", "DHIA IMANI ADRA BINTI MOHD FADZHEL",
    "FAHIM AFHAM BIN SUEFIAN", "MD JUL HAKIMI", "MIKAYLA AZZAHRA BINTI MOHD AVIENASH", "MOHAMAD AQASHA BIN ADRIAN GOH",
    "MOHAMAD ARYAN ZHAFRAN BIN MOHD SHUKRI", "MOHAMMAD KHALID PUTRA BIN ABDULLAH", "MUHAMAD AMIL BIN ABDULLAH",
    "MUHAMAD HARITH NAUFAL BIN MUHAMAD AZRUL", "MUHAMMAD ADAM AARIZ BIN MUHD. ARZIZ AFIZY", "MUHAMMAD AKMAL QAUTHAR BIN ROSMEH",
    "MUHAMMAD ARRASH FIQRIE BIN MOHD SOBRI", "MUHAMMAD HAFIZ AQEEL BIN SOPIAN", "MUHAMMAD KARL NEYDIM BIN MOHAMAD SHARIL",
    "MUHAMMAD RIZQI BIN ZAMRI", "NUR AAIRA UMAIRAH BINTI MOHD ARIFF", "NUR IZARA DANIAH BINTI RAJIM",
    "RAIF MAGOMED BIN MUHAMMAD FIRDAUS", "SHARIFA NUR AYSAH BINTI HUSIN", "SYIFAA BINTI JAMALEY", "ADIRA BINTI JAPRI",
    "MUHAMMAD IRSYAD WAZIEF BIN JIMI"
  ],
  "3 Amanah": [
    "AMMENUWELL JHONSEN JOHNLY", "AWANG KUZAIRY BIN AG. AZMI", "FADZUREEN ADELLISYAH BINTI FADILLAH AFEANDDY",
    "HEMI NUR INARA KAYYISHA BINTI HEMI AZRIN", "LEONA ROYSTONE", "MAHIRUDDIN BIN ABDULLAH", "MIKAYLA ULAYYA BINTI ABDULLAH",
    "MOHAMMAD NAFIS RIDZUAN BIN ABDULLAH", "MOHAMMAD RAYHAN WAFIEY BIN MOHD RENOZHA", "MUHAMMAD AIDAN ARIFF AMIRUL BIN ABDULLAH",
    "MUHAMMAD AIMAN BIN ABDULLAH", "MUHAMMAD AQRYLL AZHAEL BIN AIZAL", "MUHAMMAD ELMAN HAFIY BIN MOHD. ZUL HANAFIAH",
    "MUHAMMAD FATIH FATHULLAH BIN MOHD FIRDAUS", "MUHAMMAD RIZQIN IFWAT BIN RAZALI", "NAZRI BIN AFIAN",
    "NUR AISYAH BINTI MOHAMMAD HAIRUL", "NUR HANNIE HAZIYAH BINTI HANAFI", "NUR KHAYLA IRDINA BINTI ABDULLAH",
    "NUR SYUHRAH BINTI ZAINI", "NUR UFAIRAH ALEEYA BINTI MOHD. HAIRI", "NURHAWA AMANDA SUKRI BINTI ABDULLAH",
    "NURUL AYIM BATRISYAH BINTI ABDUL HALIM", "RAISHA ALISHA BINTI ABDULLAH", "SAFIYYAHTUL MARYA BINTI MOHD FIKRI",
    "SYAFEA RIZSYA BINTI MOHD SYAFAWIE", "SYARIFAH JAUHARA BINTI ABDULLAH", "WAHYUDIN JIHAD BIN JUMARDI", "MUHAMMAD TAUFIQ BIN TOBIAS"
  ],
  "3 Bestari": [
    "ADEVA RIANNE BINTI BRIAN", "AHMAD TIRMIZI BIN AMLI", "AIDAN NUR SYAM BIN ABDUL RAHMAN", "AKIF ALFIAN BIN ABDULLAH",
    "BALQIS HUMAIRAH BINTI MAZLAN", "DANIEL ASYRANI BIN ABDULLAH", "FARIZ KHAIRI BIN SUHARMAN", "FRIDAUS FELIX BIN FRANCHIS",
    "ISABELLE OLIVIA BINTI ABDULLAH", "MOHAMMAD ALNAJAR BIN ABDULLAH", "MOHAMMAD AMIRUL ZAQWAN BIN MOHD ALFIAN",
    "MUHAMMAD ALEEF FIRAS BIN MOHAMMAD MAHATHIR", "MUHAMMAD AQIL MIRZA BIN JAVIR", "MUHAMMAD HANZALAH BIN ABDULLAH",
    "MUHAMMAD IBB RAMADHAN BIN AZIZAN", "MUHAMMAD UWAISH SYAWAL BIN MOHAMMAD SABRI", "NUR AISYAH MAISARAH BINTI ABDULLAH",
    "NUR RAHADHATUL AISY BINTI SAMSUDDIN", "NURIZZARA BINTI AZHAR", "NURQUEAIRA BINTI SOBREE", "PUTRI ANIS ELISA BINTI EFINDY",
    "QHALIQ QASYAH BIN AWANG SYAHRIZAD", "QHAYRA QAISARA BINTI REZUAN", "SITI SALEHA BINTI ABDULLAH", "ZAIF AUFA ADITYA BIN MOHD FAEIZ"
  ]
};

function getGender(name: string) {
  const femaleKeywords = [
    "BINTI", "BTE", "NUR", "SITI", "PUTRI", "INTAN", "BIBI", "AINEZ", "YING",
    "HANA", "INAS", "SHARIFA", "SYIFAA", "ADIRA", "ANUM", "DHIA", "MIKAYLA",
    "IZARA", "SYARIFAH", "SAFIYYAHTUL", "RAISHA", "SYAFEA", "BALQIS", "ISABELLE",
    "ADEVA", "LEONA", "FADZUREEN"
  ];
  if (femaleKeywords.some(keyword => name.includes(keyword))) {
    return "Perempuan";
  }
  return "Lelaki";
}

async function seedFirestore() {
  console.log("Starting Firestore seeding...");
  const batch = writeBatch(db);
  const studentsRef = collection(db, "students");

  for (const [className, students] of Object.entries(classes)) {
    for (const name of students) {
      const newDocRef = doc(studentsRef);
      batch.set(newDocRef, {
        name: name.toUpperCase(),
        class: className,
        gender: getGender(name),
        archived: false
      });
    }
  }

  await batch.commit();
  console.log("Firestore seeded successfully!");
}

// Note: This script needs to be run in a browser context or with a node environment 
// that has the firebase config. For now, I'll provide this as a reference 
// and we can implement a "Seed Data" button in the UI for the user.
